name: Build & Test

on:
  push:
    branches: [ Dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest               

    env:
      Solution_Name: DynamicSepcs.sln

    steps:
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Restore
      run: dotnet restore   
     
    - name: Build
      run: dotnet build

    - name: Execute unit tests
      run: dotnet test
